=== JoanaAzevedo17/JoanaAzevedo_Portfolio/Project 2 - Implementing Text Markup and Validation in XML and DTD/DTD.dtd
<!ELEMENT TEI (teiHeader, text)>
<!ATTLIST TEI xmlns CDATA #IMPLIED>

<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>

<!ELEMENT titleStmt (title, author, respStmt)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title type CDATA #IMPLIED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT respStmt (resp, name+)>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT publicationStmt (p+)>
<!ELEMENT p (#PCDATA | intervention | locus | choice | orig | reg | prep_med | ingredient | condition | precaution | dosage | excipient | duration | citation | description_animal | italic | foreign | geoName | description_plant | ew | animal | lb | pc | drug)*>

<!ELEMENT sourceDesc (bibl)>
<!ELEMENT bibl (title+, author, date)>
<!ELEMENT date (#PCDATA)>

<!ELEMENT text (body)>
<!ELEMENT body (#PCDATA | pb | div)*>

<!ELEMENT pb EMPTY>
<!ATTLIST pb n CDATA #REQUIRED>
<!ELEMENT div (#PCDATA | figure | head | p | pb)*>

<!ELEMENT figure (graphic, figDesc)>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic url CDATA #REQUIRED>
<!ELEMENT figDesc (#PCDATA)>

<!ELEMENT head (#PCDATA | hi)*>

<!ELEMENT hi (#PCDATA | ingredient | animal | geoName | choice | orig | reg)*>

<!ELEMENT pc (#PCDATA)>
<!ELEMENT intervention (#PCDATA | dosage | prep_med | duration | pc | locus | condition | ingredient | choice | lb | citation | ew)*>
<!ELEMENT locus (#PCDATA | lb)*>

<!ELEMENT choice (orig| reg | geoName)*>
<!ELEMENT orig (#PCDATA | pc)*>
<!ELEMENT reg (#PCDATA | pc)*>

<!ELEMENT cure (#PCDATA | choice)*>
<!ELEMENT prep_med (#PCDATA | ingredient | dosage | pc | lb | precaution | intervention | choice | duration)*>
<!ELEMENT ingredient (#PCDATA | animal | locus | choice | geoName | lb | dosage | drug)*>
<!ELEMENT condition (#PCDATA | lb | locus | pc)*>
<!ELEMENT precaution (#PCDATA | lb | ingredient | pc)*>
<!ELEMENT dosage (#PCDATA | ingredient | choice | pc | lb | excipient)*>
<!ELEMENT excipient (#PCDATA)>
<!ELEMENT duration (#PCDATA | choice | cure | pc | lb)*>
<!ELEMENT citation (#PCDATA | italic)*>
<!ELEMENT description_animal (#PCDATA | geoName | lb)*>

<!ELEMENT italic (#PCDATA | foreign)*>
<!ELEMENT foreign (#PCDATA)>
<!ATTLIST foreign xml:lang CDATA #REQUIRED>

<!ELEMENT geoName (#PCDATA | lb)*>
<!ELEMENT description_plant (#PCDATA | lb | pc)*>
<!ELEMENT ew (#PCDATA)>
<!ELEMENT animal (#PCDATA)>
<!ELEMENT drug (#PCDATA)>
<!ELEMENT lb EMPTY>

=== JoanaAzevedo17/JoanaAzevedo_Portfolio/Project 2 - Implementing Text Markup and Validation in XML and DTD/Memorial_Joana_Joao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "DTD.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Memorial DeVarios Simplices</title>
                <author>Curvo Semmedo</author>
                <respStmt>
                    <resp>Transcrito e editado por</resp>
                    <name>Joana Lucas Fernandes Azevedo</name>
                    <name>João Francisco Reis Garção</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Obra publicada pela primeira vez na 3.ª edição da Polyantheia Medicinal em 1716</p>
                <p>Versão eletrónica disponível através do site:</p>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>Memorial DeVarios Simplices</title>
                    <title type="sub">Que da Índia Oriental...</title>
                    <author>Curvo Semmedo</author>
                    <date>1700</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </teiHeader>
    
    <text>
        <body>
            <pb n="10"/>
            <div>
                <figure>
                    <graphic url="pagina_10_memorial.jpg"/>
                    <figDesc>Imagem da página 10 do Memorial de Varios Simplices.</figDesc>
                </figure>
                <head><hi><ingredient>Dente de <animal>peixe mulher virgem</animal></ingredient>, e [s]uas virtudes.</hi></head>
                <p>Serve para <intervention>e[s]tancar os fluxos de [s]angue da boca</intervention> <locus>po[s]to [s]obre o peito</locus>, e para <intervention>e[s]tancar o fluxos baixos</intervention>, <locus>po[s]ta pela parte baixa.</locus><lb/>
                    Serve trazido atado no <locus>braço e[s]querdo, chegado à carne</locus><lb/>
                    <choice><orig>cõtra</orig><reg>contra</reg></choice> o ar, accidétes, e vágados.</p>
            </div>
            <div>
                <head><hi>Co[s]tella de <animal>peixe mulher virgem</animal>, e suas virtudes.</hi></head>
                <p>Serve, <prep_med>preparada em <ingredient>agua</ingredient></prep_med>, <intervention>e bebida</intervention>, <condition>para as febres, e para as dores de Pleurizes</condition><lb/>
                    pontadas, e e[s]tupores, <precaution>advertindo que naõ [s]endo virgem, naõ tem virtude.</precaution></p>
            </div>
            <div>
                <head><hi>Priapo, ou genital do <animal>cavallo marinho</animal>, e [s]uas virtudes.</hi></head>
                <p><intervention>Dando a beber</intervention> <dosage>meya oitava do <ingredient>pò do priapo do cavallo marinho</ingredient></dosage> <prep_med><dosage>mi[s]turado com<lb/>
                    [s]eis onças de agua commua</dosage> <dosage>cozida com hum pao de faveira sec(a), ou com duas oitava<lb/>
                        de <ingredient>raiz de Eroca Marinha</ingredient>, ou com ca[s]cas de rabãos</dosage></prep_med>, <condition>provoca muito a ourina [s]upprimida</condition>,<lb/>
                    com duas condiçoens: a primeira, que o doente tenha tomado primeiro que tudo<lb/>
                    <dosage><ingredient>hum vomitorio</ingredient></dosage> de <dosage>[s]eis grãos de <ingredient>Tartaro emético</ingredient></dosage>, ou <dosage>duas onças de <excipient>agua Benedicta</excipient></dosage>,<lb/>
                    <duration>[s]angrando-se ao outro dia quatro vezes</duration><locus>nos braços</locus>, <duration>e a outro dia tres</duration>, e ob[s]ervando estes<lb/>
                    con[s]elhos certamente ourin(ar)à muito o doente.</p>
            </div>
            <div>
                <head><hi>Priapo, ou genital do <animal>Veado</animal>.</hi></head>
                <p>Tem maravilho[s]a virtude para as <condition>camaras de [s]angue, e para as pontadas do Pleuriz</condition>,<lb/>
                    <intervention><dosage>dando meya oitava do [s]eu pò</dosage>, mi[s]turado com <ingredient>agua cozida com papoulas</ingredient>, <duration>continuando<pc>-</pc>o<lb/>
                        tres , ou quatro dias pela manhâa em jejum, e às noites tres horas antes de cear</duration></intervention>.</p>
            </div>
            <div>
                <head><hi>Dente de <animal>cavallo marinho</animal>, e suas virtudes.</hi></head>
                <p><ingredient>O Pò fustili[ss]imo de[s]te dente</ingredient> tem grande virtude para <condition>[s]upre[ss]oens da ourina</condition>; com<lb/>
                    tal condiçaõ que <intervention>se darà para cada vez <dosage>huma oitava delle mi[s]turado cõ meyo quartilho<lb/>
                        de <ingredient>agua cozida com raiz de e[s]p(a)rgo</ingredient>, ou com <ingredient>raiz de rilha boy</ingredient></dosage>, chamada dos latinos<lb/>
                        <citation>Ononis, ou Remora aratri</citation>, ou com <ingredient>pao de virga aurca</ingredient></intervention>: aproveita muito para as <condition>febres</condition>, <intervention><dosage>dado<lb/>
                            na me[s]ma quantidade</dosage>, <prep_med>mi[s]turado na <ingredient>agua das tisanas</ingredient></prep_med>, <locus>trazido junto da carne</locus></intervention>, tem certa<lb/>
                    qualidade occulta contra o ar. E[s]te dente tem as me[s]mas virtudes, que o dente de Engala;<lb/>
                    <locus>po[s]to sobre as cadeiras</locus>, aprove(i)ta muito para as <condition>almorreimas</condition>, <intervention>e[s]tanca o [s]angue: de qualquer<lb/>
                        parte que [s]ahir por modo de milagre: hum anel feito de[s]te dente, [s]u[s]p(e)nde o [s]angue</intervention><lb/>
                    das <condition>almorreimas</condition>, e <intervention><duration>tira as dores dellas em menos de huma hora</duration></intervention>.</p>
            </div>                          
            <pb n="11"/> 
            <div>
                <figure>
                    <graphic url="pagina_11_memorial.jpg"/>
                    <figDesc>Imagem da página 11 do Memorial de Varios Simplices.</figDesc>
                </figure>
                <head><hi><ingredient>Dente de dentro da <locus>boca</locus> do <animal>Elefante</animal></ingredient>, e [s]uas virtudes.</hi></head>
                
                <p><condition>Serve para toda a e[s]pecie de febre, para as dores de co[s]tado, para as dores de rheumati[s]m(o)</condition>,<lb/>  
                    e <prep_med>preparando<pc>-</pc>o tambem em fórma que [s]e cubra com a ma[ss]a, ou polme do<lb/>  
                        dente preparado em <ingredient>agua</ingredient>, e [s]e for ro[s]ada, [s]erá melhor, mas <precaution>deve [s]er morna</precaution></prep_med>.</p>
            </div>
            <div>
                <head><hi>Unha do <animal>graõ Be[s]ta</animal>, e [s]uas virtudes.</hi></head>
                
                <p><description_animal>O Graõ Be[s]ta he hum animal, que na língua dos Etiopes Mouros [s]e chama Nhumbo<lb/> 
                    e na língua Portugueza val o me[s]mo que animal fermo[s]o. A [s]ua fórma he de hum<lb/> 
                    perfeito cavallo em tudo menos: [s]ua cauda tem muy pouco pello, e o ca[s]co he fendido<lb/> 
                    como unha de cabra; ordinariamente naqueles contornos [s]aõ manchados como Tigres;<lb/> 
                    alguns, que [s]aõ raros, de cor ca[s]tanho claro.</description_animal></p>
                <p><precaution>Só as unhas do pè e[s]querdo [s]aõ  as que tem virtudes; as outras, [s]endo do me[s]mo animal,<lb/>  
                    naõ tem [s]erventia, e muitas vezes [s]e dà qualquer das ditas unhas, ou vende, e [s]endo do<lb/>  
                    me[s]mo animal não tem pre[s]timo; e tem a circun[s]tancia de que hade [s]er tirada a unha [s]em<lb/>  
                    [s]er metida no fogo, nem em agua quente, porque perde a virtude.</precaution></p>
                <p><description_animal>O animal he [s]ugeito a accidentes repetidos, e tem tal in[s]tincto, que a[ss]im como [s]e vê<lb/> 
                    ameaçado do accidente, mete a unha do pè e[s]querdo no ouvido, e a[ss]im que lhe passa logo a<lb/> 
                    força delle.</description_animal></p>
                <p>Serve a unha do grão be[s]ta, <intervention>trazendo<pc>-</pc>a <locus>junto à carne do um[s]culo do braço e[s]querdo</locus></intervention>, <locus>ou<lb/> 
                    ao pe[s]coço, e ainda [s]obre o peito, ou no dedo da maõ e[s]querda</locus>, <intervention>enga[s]toada em ouro, de<lb/> 
                        forte <locus>que a unha toque na carne</locus></intervention>; <condition>[s]erve contra os accidentes de gotta coral, e vàgados, e<lb/> 
                            contra o ar</condition>. <intervention><prep_med>Preparada em <ingredient>agua</ingredient>, e bebida</prep_med> <condition>[s]erve contra o veneno</condition>, e contra as febres<lb/> 
                                intermitentes</intervention>.</p>
                <p>Nos <condition>accidentes de a[s]thma</condition> <intervention>[s]e darà <dosage>hum escrúpulo de pó da dita unha mi[s]turado com<lb/> 
                    huma chicara de agua de cereijas negras</dosage></intervention>: por quanto a <condition>a[s]thma</condition> he hum acidente [de gotta<lb/> 
                    coral do bese, <citation>como diz Vanelmoncio: <italic><foreign xml:lang="lat">Asthma est caducum pulmonis</foreign></italic></citation>.</p>
            </div>
            <div>
                <head><hi><ingredient>O[ss]os do e[s]pinhaço da <animal>Cobra Zuchi</animal></ingredient>, ou Zuichi, e [s]uas virtudes.</hi></head>
                
                <p><description_animal><geoName>Em Angola</geoName> [s]e criaõ humas cobras, a que os naturaes chamaõ Zuchi, que quer dizer<lb/>
